# blog.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: assignment2

---

kind: Service
apiVersion: v1
metadata:
  name: blog-service
  namespace: assignment2
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31234

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: assignment2
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  
  # Pod
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: db-service
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
        ports:
        - containerPort: 80
      volumes:
      - name: wp-data


