# db.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: assignment2

---

kind: Service
apiVersion: v1
metadata:
  name: db-service
  namespace: assignment2
  labels:
    app: db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: assignment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  
  # Pod
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-data
